language: python

python:
 - "3.6"

env:
  global:
    PIPENV_IGNORE_VIRTUALENVS=1

install:
 - pip install -U --process-dependency-links Red-DiscordBot[voice]
 - pip install -U --process-dependency-links git+https://github.com/Rapptz/discord.py@rewrite
 - pip install yarl==0.18.0
 - pip install black

script:
 - black --check -l 100 .
 - python3 -m compileall .
 - python3 info_deploy.py