language: python

python:
 - "3.5"
 - "3.6"

env:
  global:
    PIPENV_IGNORE_VIRTUALENVS=1

install:
 - pip install -U --process-dependency-links Red-DiscordBot[voice]
 - pip install -U --process-dependency-links git+https://github.com/Rapptz/discord.py@rewrite
 - pip install -U pipenv
 - pipenv install --dev

script:
 - pipenv run tox
 - python3 -m compileall .
 - python3 info_deploy.py