language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
 - pip install -U Red-DiscordBot
 - pip install yarl==0.18.0
 - pip install black
 - pip install python-dateutil

script:
 - make compile
 - make stylecheck
