language: python
python:
 - "3.5"
 - "3.6"
install:
 - pip install -U --process-dependency-links Red-DiscordBot[voice]
 - pip install -U pipenv
 - pipenv install --dev
script:
 - pipenv run tox
 - python3 -m compileall .
 - python3 info_deploy.py