blank_issues_enabled: true
contact_links:
  - name: 3rd party cog support server
    url: https://discord.gg/GET4DVk
    about: The Discord server for support with 3rd party cogs. Head to the \#support_laggrons-dumb-cogs channel
